ARG BASE_IMAGE=stevendargaville/petsc_nvidia

FROM ${BASE_IMAGE}
# Checkout the main branch by default
ARG BRANCH=main
# Use the optimised petsc build by default
ARG ARCH=arch-linux-nvidia
# Compile PFLARE with optimisation by default
ARG OPT="-O3"

LABEL maintainer="Steven Dargaville"
LABEL description="PFLARE_nvidia"

# If you want to debug inside the container
# RUN apt-get update && apt-get install -y valgrind 

ENV CHECKOUT_BRANCH=$BRANCH
ENV PETSC_ARCH=$ARCH
ENV OPT_FLAG=$OPT

WORKDIR /build

# Clone PFLARE and run all the tests
RUN set -e; \
    echo "Cloning branch: ${CHECKOUT_BRANCH}" && \
    git clone --branch ${CHECKOUT_BRANCH} https://github.com/stevendargaville/PFLARE.git && \
    cd PFLARE && \
    make OPT=${OPT_FLAG} && make OPT=${OPT_FLAG} tests

WORKDIR /build/PFLARE
