ARG BASE_IMAGE=stevendargaville/petsc_64_bit
FROM ${BASE_IMAGE}

# If you want to debug inside the container
# RUN apt-get update && apt-get install -y valgrind 

# Clone PFLARE and build the tests
RUN git clone https://github.com/stevendargaville/PFLARE.git
RUN cd PFLARE && make && make build_tests

WORKDIR /build/PFLARE

LABEL maintainer='Steven Dargaville'
LABEL description='PFLARE_64_bit'