ARG BASE_IMAGE=stevendargaville/petsc_kokkos

FROM ${BASE_IMAGE}
# Checkout the main branch by default
ARG BRANCH=main
# Use the optimised petsc build by default
ARG ARCH=arch-linux-c-opt

LABEL maintainer="Steven Dargaville"
LABEL description="PFLARE_kokkos"

ENV CHECKOUT_BRANCH=$BRANCH
ENV PETSC_ARCH=$ARCH
# This turns on checks between kokkos and cpu versions
ENV PFLARE_KOKKOS_DEBUG=1
# Ensure any test failures are caught and the build fails
# Also force any test that can to use the kokkos types
# Many tests will output a warning that some of these options are unused but that can be ignored
ENV PETSC_OPTIONS="-on_error_abort -mat_type aijkokkos -vec_type kokkos -dm_mat_type aijkokkos -dm_vec_type kokkos"

WORKDIR /build

# Clone PFLARE and run all the tests
RUN set -e; \
    echo "Cloning branch: ${CHECKOUT_BRANCH}" && \
    git clone --branch ${CHECKOUT_BRANCH} https://github.com/stevendargaville/PFLARE.git && \
    cd PFLARE && \
    make && make tests

WORKDIR /build/PFLARE
